// Code generated by bpf2go; DO NOT EDIT.
//go:build mips || mips64 || ppc64 || s390x

package bpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type lbBackendInfo struct {
	_      structs.HostLayout
	Ipv4   uint32
	Port   uint16
	Pad    uint16
	Mac    [6]uint8
	Pad2   [2]uint8
	Weight uint32
}

type lbLbConfig struct {
	_            structs.HostLayout
	Vip          uint32
	Vport        uint16
	Pad          uint16
	BackendCount uint32
	SrcMac       [6]uint8
	Pad2         [2]uint8
}

type lbStatsCounter struct {
	_         structs.HostLayout
	RxPackets uint64
	RxBytes   uint64
}

// Names of all BPF objects in the ELF.
//
// Used for safe lookups in a Collection or CollectionSpec.
const (
	lbMapBackendIpsMap = "backend_ips_map"
	lbMapBackendMap    = "backend_map"
	lbMapConfigMap     = "config_map"
	lbMapCountersMap   = "counters_map"
	lbProgXdpLbIngress = "xdp_lb_ingress"
	lbProgXdpVethSnat  = "xdp_veth_snat"
)

// loadLb returns the embedded CollectionSpec for lb.
func loadLb() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_LbBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load lb: %w", err)
	}

	return spec, err
}

// loadLbObjects loads lb and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*lbObjects
//	*lbPrograms
//	*lbMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadLbObjects(obj any, opts *ebpf.CollectionOptions) error {
	spec, err := loadLb()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// lbSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type lbSpecs struct {
	lbProgramSpecs
	lbMapSpecs
	lbVariableSpecs
}

// lbProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type lbProgramSpecs struct {
	XdpLbIngress *ebpf.ProgramSpec `ebpf:"xdp_lb_ingress"`
	XdpVethSnat  *ebpf.ProgramSpec `ebpf:"xdp_veth_snat"`
}

// lbMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type lbMapSpecs struct {
	BackendIpsMap *ebpf.MapSpec `ebpf:"backend_ips_map"`
	BackendMap    *ebpf.MapSpec `ebpf:"backend_map"`
	ConfigMap     *ebpf.MapSpec `ebpf:"config_map"`
	CountersMap   *ebpf.MapSpec `ebpf:"counters_map"`
}

// lbVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type lbVariableSpecs struct {
}

// lbObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadLbObjects or ebpf.CollectionSpec.LoadAndAssign.
type lbObjects struct {
	lbPrograms
	lbMaps
	lbVariables
}

func (o *lbObjects) Close() error {
	return _LbClose(
		&o.lbPrograms,
		&o.lbMaps,
	)
}

// lbMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadLbObjects or ebpf.CollectionSpec.LoadAndAssign.
type lbMaps struct {
	BackendIpsMap *ebpf.Map `ebpf:"backend_ips_map"`
	BackendMap    *ebpf.Map `ebpf:"backend_map"`
	ConfigMap     *ebpf.Map `ebpf:"config_map"`
	CountersMap   *ebpf.Map `ebpf:"counters_map"`
}

func (m *lbMaps) Close() error {
	return _LbClose(
		m.BackendIpsMap,
		m.BackendMap,
		m.ConfigMap,
		m.CountersMap,
	)
}

// lbVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadLbObjects or ebpf.CollectionSpec.LoadAndAssign.
type lbVariables struct {
}

// lbPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadLbObjects or ebpf.CollectionSpec.LoadAndAssign.
type lbPrograms struct {
	XdpLbIngress *ebpf.Program `ebpf:"xdp_lb_ingress"`
	XdpVethSnat  *ebpf.Program `ebpf:"xdp_veth_snat"`
}

func (p *lbPrograms) Close() error {
	return _LbClose(
		p.XdpLbIngress,
		p.XdpVethSnat,
	)
}

func _LbClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed lb_bpfeb.o
var _LbBytes []byte
